/*
 * Core API
 * Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.  With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TCIAIds
 */
public class TCIAIdsTest {
    private final TCIAIds model = new TCIAIds();

    /**
     * Model tests for TCIAIds
     */
    @Test
    public void testTCIAIds() {
        // TODO: test TCIAIds
    }

    /**
     * Test the property 'tagIds'
     */
    @Test
    public void tagIdsTest() {
        // TODO: test tagIds
    }

    /**
     * Test the property 'teammateIds'
     */
    @Test
    public void teammateIdsTest() {
        // TODO: test teammateIds
    }

    /**
     * Test the property 'channelIds'
     */
    @Test
    public void channelIdsTest() {
        // TODO: test channelIds
    }

    /**
     * Test the property 'inboxIds'
     */
    @Test
    public void inboxIdsTest() {
        // TODO: test inboxIds
    }

    /**
     * Test the property 'teamIds'
     */
    @Test
    public void teamIdsTest() {
        // TODO: test teamIds
    }

    /**
     * Test the property 'accountIds'
     */
    @Test
    public void accountIdsTest() {
        // TODO: test accountIds
    }

}
